'use strict';
/**
 * Yosegi の固定バイト列を書き出す。
 *
 *   node vectors.js
 *
 * 出力: research/vectors/yosegi.json
 *
 * なぜ要るか。形式は契約で、契約は**独立した2つの読み手**が同じバイト列に同じ意味を
 * 見たときに初めて確かめられる。Kotlin と Swift が互いのコードを見ずに、この1つの
 * ファイルだけを見て一致するなら、仕様が正しいと言える。
 *
 * envelope と backup には既に formats.json があり、Yosegi だけ無かった。
 * 照合の相手がいないまま2つ目の実装を書くと、**間違いが揃ってしまう**。
 *
 * **このファイルを書き換えるのは、v2 を作るときだけ。**
 * 値が変わったら、それは形式が変わったということで、凍結を破っている。
 */
const fs = require('fs');
const path = require('path');
const yosegi = require('./yosegi.js');

const OUT = path.join(__dirname, '..', 'vectors', 'yosegi.json');

// 実際の Firestore の形に合わせる。id は base62 20文字、uid は 28文字。
const CONVERSATION = 'aB3dEf6hIj9lMn2pQr5t';
const MEMBERS = [
  'K1mN4pQ7rS0tU3vW6xY9zA2bC5dE',
  'F8gH1jK4lM7nP0qR3sT6uV9wX2yZ',
  'B5cD8eF1gH4jK7lM0nP3qR6sT9uV',
];
const STICKERS = ['sticker.wave', 'sticker.thumbsup', 'sticker.cry'];

const BASE = 1755390600000;

// 一つずつ、別の場所を踏むように作る。
const CASES = [
  {
    name: 'text only',
    note: '一番短い形。ここが崩れたら他は全部崩れる',
    messages: [
      { id: 'Msg0000000000000001A', senderId: MEMBERS[0], timestampMs: BASE, status: 'Sent', text: 'おはよう' },
    ],
  },
  {
    name: 'three in one frame',
    note: '時刻差が zigzag で詰まること。2通目以降は直前からの差',
    messages: [
      { id: 'Msg0000000000000002B', senderId: MEMBERS[0], timestampMs: BASE, status: 'Read', text: 'いま駅' },
      { id: 'Msg0000000000000003C', senderId: MEMBERS[1], timestampMs: BASE + 41000, status: 'Read', text: 'りょ' },
      { id: 'Msg0000000000000004D', senderId: MEMBERS[0], timestampMs: BASE + 95000, status: 'Delivered', text: '5分で着く' },
    ],
  },
  {
    name: 'out of order timestamps',
    note: '**負の差分。** 順不同で届くことがあるので zigzag が要る',
    messages: [
      { id: 'Msg0000000000000005E', senderId: MEMBERS[1], timestampMs: BASE + 60000, status: 'Sent', text: 'あとで' },
      { id: 'Msg0000000000000006F', senderId: MEMBERS[0], timestampMs: BASE + 20000, status: 'Sent', text: 'これ先に届いた' },
    ],
  },
  {
    name: 'emoji and multibyte',
    note: '長さはバイト数であって文字数ではない',
    messages: [
      { id: 'Msg0000000000000007G', senderId: MEMBERS[2], timestampMs: BASE, status: 'Sent', text: 'おつかれ🌙 また明日ね' },
    ],
  },
  {
    name: 'sticker from catalogue',
    note: 'カタログにあるスタンプは索引1バイト',
    messages: [
      { id: 'Msg0000000000000008H', senderId: MEMBERS[1], timestampMs: BASE, status: 'Sent', stickerId: 'sticker.cry' },
    ],
  },
  {
    name: 'sticker outside catalogue',
    note: 'カタログに無いものは文字列で送る。索引を勝手に作らない',
    messages: [
      { id: 'Msg0000000000000009I', senderId: MEMBERS[1], timestampMs: BASE, status: 'Sent', stickerId: 'sticker.unknown' },
    ],
  },
  {
    name: 'reply',
    note: '複合ブロック。中の長さは、その中で閉じる',
    messages: [
      {
        id: 'Msg0000000000000010J', senderId: MEMBERS[0], timestampMs: BASE, status: 'Sent', text: 'それで大丈夫',
        replyTo: { messageId: 'Msg0000000000000002B', senderName: 'ゆい', excerpt: 'いま駅' },
      },
    ],
  },
  {
    name: 'sender outside the member list',
    note: '**0xFF の経路。** 参加者一覧に無い送信者は uid をそのまま送る',
    messages: [
      { id: 'Msg0000000000000011K', senderId: 'Z9yX6wV3uT0sR7qP4nM1lK8jH5gF', timestampMs: BASE, status: 'Sent', text: '退会済みの人' },
    ],
  },
  {
    name: 'every status',
    note: '状態は1バイト。範囲外は拒否される側',
    messages: ['Sending', 'Sent', 'Delivered', 'Read', 'Failed'].map((s, i) => ({
      id: 'Msg000000000000001' + (2 + i) + 'L', senderId: MEMBERS[i % 3],
      timestampMs: BASE + i * 1000, status: s, text: '状態' + i,
    })),
  },
  {
    name: 'empty text',
    note: '長さ0の文字列。省略とは違う',
    messages: [
      { id: 'Msg0000000000000017M', senderId: MEMBERS[0], timestampMs: BASE, status: 'Sent', text: '' },
    ],
  },
];

const ctx = yosegi.makeContext(CONVERSATION, MEMBERS, STICKERS);

const out = {
  note: 'Generated by research/wire/vectors.js. Any implementation of Yosegi v1 must produce '
    + 'and read these exactly. See docs/YOSEGI_V1_SPEC.md. Do not edit by hand.',
  version: 1,
  conversationId: CONVERSATION,
  memberIds: MEMBERS,
  stickerCatalogue: STICKERS,
  cases: CASES.map((c) => {
    const frame = Buffer.from(yosegi.encode(c.messages, ctx));
    // 書き出す前に、自分で読み返せることを確かめる。
    const back = yosegi.decode(frame, ctx);
    if (back.length !== c.messages.length) throw new Error(c.name + ': 通数が合わない');
    return {
      name: c.name,
      note: c.note,
      messages: c.messages,
      hex: frame.toString('hex'),
      bytes: frame.length,
    };
  }),
};

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, JSON.stringify(out, null, 2) + '\n');

console.log(OUT);
for (const c of out.cases) {
  console.log('  ' + c.name.padEnd(30) + String(c.bytes).padStart(5) + ' B');
}
